// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAM1N_I6AjQpvpGUuxW-UHi8rOdWoPgxoo',
    appId: '1:547511206892:web:53ecc5e187584427b4b6c9',
    messagingSenderId: '547511206892',
    projectId: 'bliss-recruitment-2025',
    authDomain: 'bliss-recruitment-2025.firebaseapp.com',
    storageBucket: 'bliss-recruitment-2025.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCi1i_Qdu1e4qnlKm80g-jQg1kIH68uufw',
    appId: '1:547511206892:android:c4a1d963224a17aeb4b6c9',
    messagingSenderId: '547511206892',
    projectId: 'bliss-recruitment-2025',
    storageBucket: 'bliss-recruitment-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrrwu3KErLdK7sdCQ68t5OG03kKrsWCEg',
    appId: '1:547511206892:ios:4282c0735730c181b4b6c9',
    messagingSenderId: '547511206892',
    projectId: 'bliss-recruitment-2025',
    storageBucket: 'bliss-recruitment-2025.firebasestorage.app',
    iosBundleId: 'com.example.blissMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrrwu3KErLdK7sdCQ68t5OG03kKrsWCEg',
    appId: '1:547511206892:ios:4282c0735730c181b4b6c9',
    messagingSenderId: '547511206892',
    projectId: 'bliss-recruitment-2025',
    storageBucket: 'bliss-recruitment-2025.firebasestorage.app',
    iosBundleId: 'com.example.blissMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAM1N_I6AjQpvpGUuxW-UHi8rOdWoPgxoo',
    appId: '1:547511206892:web:fedd50078e1af4d2b4b6c9',
    messagingSenderId: '547511206892',
    projectId: 'bliss-recruitment-2025',
    authDomain: 'bliss-recruitment-2025.firebaseapp.com',
    storageBucket: 'bliss-recruitment-2025.firebasestorage.app',
  );
}
