const fs = require('fs');
const path = require('path');
const PDFDocument = require('pdfkit');

async function generateContractPdf(contract) {
  return new Promise((resolve, reject) => {
    try {
      const uploadsDir = path.join(__dirname, '..', 'uploads', 'contracts');
      fs.mkdirSync(uploadsDir, { recursive: true });

      const fileName = `${contract.contractId}.pdf`;
      const filePath = path.join(uploadsDir, fileName);

      const doc = new PDFDocument({ size: 'A4', margin: 50 });
      const stream = fs.createWriteStream(filePath);
      doc.pipe(stream);

      // Header
      doc.image(path.join(__dirname, '..', 'assets', 'images', 'logo.png'), 50, 45, { width: 120 }).moveDown(2);
      doc.fontSize(20).text('Bliss Connect Employment Contract', { align: 'center' });
      doc.moveDown();

      doc.fontSize(12).text(`Contract ID: ${contract.contractId}`);
      doc.text(`Employer: ${contract.employerName || contract.companyName || contract.employerId}`);
      doc.text(`Candidate: ${contract.candidateName || contract.candidateId}`);
      doc.text(`Job Position: ${contract.jobPosition || contract.jobDescription || 'N/A'}`);
      doc.text(`Country: ${contract.jobCountry || 'N/A'}`);
      doc.moveDown();

      doc.fontSize(14).text('Contract Terms', { underline: true });
      doc.moveDown(0.5);

      const terms = [];
      terms.push(`Salary: ${contract.salary || 'N/A'}`);
      terms.push(`Contract Period (years): ${contract.contractPeriodYears || 'N/A'}`);
      terms.push(`Working Hours: ${contract.workingHours || 'N/A'}`);
      terms.push(`Accommodation: ${contract.accommodation || 'N/A'}`);
      terms.push(`Medical Cover: ${contract.medicalCover || 'N/A'}`);
      terms.push(`Air Ticket Responsibility: ${contract.airTicket || 'N/A'}`);
      terms.forEach((t) => doc.fontSize(12).text(`- ${t}`));

      doc.moveDown();
      doc.text('Special Terms:', { underline: true });
      doc.moveDown(0.5);
      doc.fontSize(12).text(contract.specialTerms || 'None');

      doc.addPage();
      doc.fontSize(12).text('Signatures', { underline: true });
      doc.moveDown(2);

      doc.text('Employer Signature:', 50, doc.y);
      if (contract.employerSignatureUrl) {
        try {
          const sigPath = path.join(__dirname, '..', contract.employerSignatureUrl.replace(/^\//, ''));
          if (fs.existsSync(sigPath)) {
            doc.image(sigPath, 50, doc.y + 10, { width: 200 });
          }
        } catch (err) {
          // ignore signature image errors
        }
      }

      doc.moveDown(6);

      doc.text('Candidate Signature:', 50, doc.y);
      if (contract.candidateSignatureUrl) {
        try {
          const sigPath = path.join(__dirname, '..', contract.candidateSignatureUrl.replace(/^\//, ''));
          if (fs.existsSync(sigPath)) {
            doc.image(sigPath, 50, doc.y + 10, { width: 200 });
          }
        } catch (err) {
          // ignore
        }
      }

      doc.moveDown(4);
      doc.fontSize(10).text(`Generated by Bliss Connect on ${new Date().toISOString()}`, { align: 'right' });

      doc.end();

      stream.on('finish', () => {
        resolve({ filePath, fileName });
      });

      stream.on('error', (err) => reject(err));
    } catch (err) {
      reject(err);
    }
  });
}

module.exports = { generateContractPdf };
