import '../models/job_model.dart';

class JobService {
  Future<List<Job>> getJobs() async {
    await Future.delayed(const Duration(seconds: 1)); // simulate loading

    return [
      // Dubai Housemaids
      Job(
        id: '1',
        employerId: 'emp1',
        jobTitle: 'Housemaid',
        companyName: 'bliss connect',
        location: 'Dubai',
        country: 'UAE',
        salary: 1000,
        currency: 'AED',
        candidateCommission: 80000,
        employerFee: 1000,
        experienceLevel: 'Fresher',
        vacancies: 30,
        featured: true,
        localOrInternational: 'International',
      ),
      Job(
        id: '2',
        employerId: 'emp1',
        jobTitle: 'Housemaid',
        companyName: 'bliss connect',
        location: 'Dubai',
        country: 'UAE',
        salary: 1200,
        currency: 'AED',
        candidateCommission: 80000,
        employerFee: 1000,
        experienceLevel: 'Experienced',
        vacancies: 30,
        featured: true,
        localOrInternational: 'International',
      ),

      // Qatar Housemaids
      Job(
        id: '3',
        employerId: 'emp2',
        jobTitle: 'Housemaid',
        companyName: 'bliss connect',
        location: 'Doha',
        country: 'Qatar',
        salary: 1000,
        currency: 'QAR',
        candidateCommission: 80000,
        employerFee: 1000,
        experienceLevel: 'Fresher',
        vacancies: 20,
        featured: false,
        localOrInternational: 'International',
      ),
      Job(
        id: '4',
        employerId: 'emp2',
        jobTitle: 'Housemaid',
        companyName: 'bliss connect',
        location: 'Doha',
        country: 'Qatar',
        salary: 1100,
        currency: 'QAR',
        candidateCommission: 80000,
        employerFee: 1000,
        experienceLevel: 'Experienced',
        vacancies: 20,
        featured: false,
        localOrInternational: 'International',
      ),

      // Oman Housemaids
      Job(
        id: '5',
        employerId: 'emp3',
        jobTitle: 'Housemaid',
        companyName: 'bliss connect',
        location: 'Muscat',
        country: 'Oman',
        salary: 90,
        currency: 'OMR',
        candidateCommission: 0,
        employerFee: 2000,
        experienceLevel: 'Fresher',
        vacancies: 15,
        featured: false,
        localOrInternational: 'International',
      ),
      Job(
        id: '6',
        employerId: 'emp3',
        jobTitle: 'Housemaid',
        companyName: 'bliss connect',
        location: 'Muscat',
        country: 'Oman',
        salary: 100,
        currency: 'OMR',
        candidateCommission: 0,
        employerFee: 2000,
        experienceLevel: 'Experienced',
        vacancies: 15,
        featured: false,
        localOrInternational: 'International',
      ),

      // Jordan Housemaids
      Job(
        id: '7',
        employerId: 'emp4',
        jobTitle: 'Housemaid',
        companyName: 'bliss connect',
        location: 'Amman',
        country: 'Jordan',
        salary: 225,
        currency: 'USD',
        candidateCommission: 0,
        employerFee: 2500,
        experienceLevel: 'Fresher',
        vacancies: 10,
        featured: false,
        localOrInternational: 'International',
      ),
      Job(
        id: '8',
        employerId: 'emp4',
        jobTitle: 'Housemaid',
        companyName: 'bliss connect',
        location: 'Amman',
        country: 'Jordan',
        salary: 250,
        currency: 'USD',
        candidateCommission: 0,
        employerFee: 2500,
        experienceLevel: 'Experienced',
        vacancies: 10,
        featured: false,
        localOrInternational: 'International',
      ),

      // Bahrain Housemaids
      Job(
        id: '9',
        employerId: 'emp5',
        jobTitle: 'Housemaid',
        companyName: 'bliss connect',
        location: 'Manama',
        country: 'Bahrain',
        salary: 100,
        currency: 'BHD',
        candidateCommission: 0,
        employerFee: 2500,
        experienceLevel: 'Fresher',
        vacancies: 10,
        featured: false,
        localOrInternational: 'International',
      ),
      Job(
        id: '10',
        employerId: 'emp5',
        jobTitle: 'Housemaid',
        companyName: 'bliss connect',
        location: 'Manama',
        country: 'Bahrain',
        salary: 110,
        currency: 'BHD',
        candidateCommission: 0,
        employerFee: 2500,
        experienceLevel: 'Experienced',
        vacancies: 10,
        featured: false,
        localOrInternational: 'International',
      ),

      // Iraq Housemaids
      Job(
        id: '11',
        employerId: 'emp6',
        jobTitle: 'Housemaid',
        companyName: 'bliss connect',
        location: 'Baghdad',
        country: 'Iraq',
        salary: 250,
        currency: 'USD',
        candidateCommission: 0,
        employerFee: 2500,
        experienceLevel: 'Fresher',
        vacancies: 10,
        featured: false,
        localOrInternational: 'International',
      ),
      Job(
        id: '12',
        employerId: 'emp6',
        jobTitle: 'Housemaid',
        companyName: 'bliss connect',
        location: 'Baghdad',
        country: 'Iraq',
        salary: 300,
        currency: 'USD',
        candidateCommission: 0,
        employerFee: 2500,
        experienceLevel: 'Experienced',
        vacancies: 10,
        featured: false,
        localOrInternational: 'International',
      ),

      // Lebanon Housemaids
      Job(
        id: '13',
        employerId: 'emp7',
        jobTitle: 'Housemaid',
        companyName: 'bliss connect',
        location: 'Beirut',
        country: 'Lebanon',
        salary: 200,
        currency: 'USD',
        candidateCommission: 0,
        employerFee: 2500,
        experienceLevel: 'Fresher',
        vacancies: 10,
        featured: false,
        localOrInternational: 'International',
      ),
      Job(
        id: '14',
        employerId: 'emp7',
        jobTitle: 'Housemaid',
        companyName: 'bliss connect',
        location: 'Beirut',
        country: 'Lebanon',
        salary: 250,
        currency: 'USD',
        candidateCommission: 0,
        employerFee: 2500,
        experienceLevel: 'Experienced',
        vacancies: 10,
        featured: false,
        localOrInternational: 'International',
      ),
    ];
  }
}
